---
title: "MEM package - Predicao influenza"
output: html_notebook
---


```{r}
#AI Flu Surveil
library(mem)
# run the app:
#memapp::runmemapp()
```

```{r}
data(flucyl)
# Data of the last season
# uncomment to execute
#full.series.graph(flucyl)
```
```{r}
data(flucyl)
# Finds the timing of the first season: 2001/2002
epi <- memmodel(flucyl[1:7])
print(epi)
summary(epi)
plot(epi)
```


```{r}
#Parametros##

#Duracao epidemia, primeira linha da saida codigo abaixo 
epi[["ci.length"]]

#Comeco epidemia, segunda linha da saida codigo abaixo 
epi[["ci.start"]]

#Epidemic trasholds, taxa inicio e fim
epi[["epidemic.thresholds"]]

#Intensidade, media alta e baixa das taxas
epi[["intensity.thresholds"]]

#curva tipica de epidemia
plot(epi$typ.curve[,2])

#limites de confianca da curva tipica de epidemia
#limite inferior
plot(epi$typ.curve[,1])

#limite superior
plot(epi$typ.curve[,3])

```


```{r}
# Carregar pacotes
library(mem)
library(ggplot2)
library(dplyr)
library(tidyr)

# Verificar os dados do modelo MEM
head(epi$data)  # Verificar a estrutura dos dados
colnames(epi$data)  # Identificar nomes corretos das colunas

# Transformar de formato amplo para longo

data_mem = epi$data
data_mem$week = as.numeric(row.names(data_mem))

df_long <- data_mem %>%
  pivot_longer(
    cols = -week,  # Mantemos a coluna "week" fixa
    names_to = "season",  # Criamos uma coluna chamada "season" com os nomes das temporadas
    values_to = "rate"  # Criamos uma coluna chamada "rate" com os valores das taxas
  )
# Criar o gráfico no ggplot2
ggplot(df_long, aes(x = week, y = rate, group = season, color = season)) +
  geom_line(size = 1) +
  labs(title = "Rate per week",
       x = "Week",
       y = "Weekly Rate",
       color = "Season") +
  theme_minimal()





df_plot <- df_long%>%
  group_by(week) %>%
  summarise(mean_rate = mean(rate, na.rm = TRUE))  # Média das taxas padronizadas

# Criando o gráfico com ggplot2
ggplot(df_plot, aes(x = week, y = mean_rate)) +
  geom_line(color = "blue", size = 1) +
  geom_point(color = "red") +
  labs(title = "Expected influenza epidemic",
       x = "Week",
       y = "Weekly Rate") +
  theme_minimal()


```
##Selecionando Argentina

```{r}
library(dplyr)
Argentina = AmericaSul_ILI %>% filter (COUNTRY_CODE=="ARG", AGEGROUP_CODE=="All", CASE_INFO=="ILI",MMWR_YEAR<2024) %>% select(MMWR_YEAR,MMWR_WEEK,COUNTRY_AREA_TERRITORY,rate_per10k_habitant,Population)

Fluid_AL_ARG = Fluid_AL %>% filter (COUNTRY_CODE=="ARG", AGEGROUP_CODE=="All", CASE_INFO=="ILI",MMWR_YEAR==2024) %>% select(MMWR_YEAR,MMWR_WEEK,COUNTRY_AREA_TERRITORY,REPORTED_CASES)

Fluid_AL_ARG$Population=unique(AmericaSul_ILI$Population[AmericaSul_ILI$COUNTRY_CODE=="ARG"& AmericaSul_ILI$AGEGROUP_CODE=="All"& AmericaSul_ILI$CASE_INFO=="ILI"&AmericaSul_ILI$MMWR_YEAR==2024])

Fluid_AL_ARG$rate_per10k_habitant=(Fluid_AL_ARG$REPORTED_CASES/Fluid_AL_ARG$Population)*10000


Argentina = rbind(Argentina,Fluid_AL_ARG%>%select(MMWR_YEAR,MMWR_WEEK,COUNTRY_AREA_TERRITORY,rate_per10k_habitant,Population))

#Taxa por 100 mil habitantes
Argentina_mem_data = data.frame(year = Argentina$MMWR_YEAR, week=Argentina$MMWR_WEEK,rates=Argentina$rate_per10k_habitant*10)

#Taxa por 100 mil habitantes
```

```{r}
library(mem)
library(tidyr)
# Transform data
newdata_Argentina <- Argentina_mem_data %>% filter(week<53)%>%
  pivot_wider(names_from = year, values_from = rates)

row.names(newdata_Argentina) = newdata_Argentina$week

newdata_Argentina$week = NULL


write.csv(newdata_Argentina, "C:\\Users\\Daniela\\Downloads\\Argentina.csv")


epi <- memmodel(newdata_Argentina[1:52,4:13],i.type.threshold = 3, i.type.intensity = 3, i.type.curve = 3)
print(epi)
summary(epi)
plot(epi)

```

##Graficos para o aplicativo
```{r}
library(ggplot2)
library(knitr)
data=epi$data
data$week=as.numeric(row.names(epi$data))

df_long <- data %>%
  pivot_longer(
    cols = -week,  # Mantemos a coluna "week" fixa
    names_to = "season",  # Criamos uma coluna chamada "season" com os nomes das temporadas
    values_to = "rate"  # Criamos uma coluna chamada "rate" com os valores das taxas
  )
# Criar o gráfico no ggplot2
graf1= 
  ggplot(df_long, aes(x = week, y = rate, group = season, color = season)) +
  geom_line(size = 1, na.rm = TRUE) +
  labs(title = "Rate per 100.000 habitants",
       x = "Week",
       y = "Weekly Rate",
       color = "Season") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"), plot.title = element_text(hjust=0.5), legend.title = element_blank(), legend.position = "right",
    legend.direction = "vertical",
    legend.key.size = unit(0.4, "cm"),
    legend.text = element_text(size = 9),
    legend.spacing.x = unit(0.2, "cm"))+
  scale_fill_viridis_d()


graf1

data=as.data.frame(epi$typ.curve[,2])
data$week=as.numeric(row.names(data))
colnames(data)[1] = "rate"
data$lower=unlist(epi$typ.curve[,1])
data$upper=unlist(epi$typ.curve[,3])



medium=round(epi[["intensity.thresholds"]][1],1)
high=round(epi[["intensity.thresholds"]][2],1)
very_high=round(epi[["intensity.thresholds"]][3],1)

# Criando o gráfico com ggplot2
graf2=ggplot(data, aes(x = week, y = rate)) +
  geom_line(color = "blue", size = 1) +
  geom_hline(yintercept = c(medium,high,very_high), linetype = "dashed", color = c("darkgreen","darkorange","darkred"))+
  annotate("text", x = c(10,10,10), y = c(medium,high,very_high) + 2, label = c( paste("medium =", round(medium, 1)),paste("high =", round(high, 1)), paste("very high =", round(very_high, 1))),color = c("darkgreen","darkorange","darkred"))  +
  labs(title = "Mean incidence curve",
       x = "Week",
       y = "Weekly Rate") +
  geom_ribbon(aes(ymin=lower,   ymax=upper), linetype=2, alpha=0.1)+
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"),legend.position = "bottom", legend.justification = "left", legend.text = element_text(size = 10), plot.title = element_text(hjust=0.5), legend.title = element_blank())

library(ggplot2)
library(gridExtra)

grid.arrange(graf1 , graf2 , ncol=2)
```
##Duracao epidemia
```{r}
#Parametros##

#Duracao epidemia, primeira linha da saida codigo abaixo 
epi[["ci.length"]]
```

##Comeco epidemia
```{r}
#Comeco epidemia, segunda linha da saida codigo abaixo 
epi[["ci.start"]]
```

##Taxa inicio e fim da epidemia
```{r}
#Epidemic trasholds, taxa inicio e fim
epi[["epidemic.thresholds"]]
```


#Intensidade, media alta e baixa das taxas
```{r}
epi[["intensity.thresholds"]]
```

```

